# Create .env file with proper UTF-8 encoding
with open('.env', 'w', encoding='utf-8') as f:
    f.write('Username=User\n')
    f.write('Assistantname=Bloom\n')
    f.write('GroqAPIKey=YOUR_GROQ_API_KEY_HERE\n')  # Get free at https://console.groq.com
    f.write('CohereAPIKey=YOUR_COHERE_API_KEY_HERE\n')  # Get free at https://dashboard.cohere.com (OPTIONAL)
    f.write('HuggingFaceAPIKey=YOUR_HUGGINGFACE_TOKEN_HERE\n')  # Get free at https://huggingface.co/settings/tokens
    f.write('InputLanguage=en-US\n')
    f.write('AssistantVoice=en-US-AriaNeural\n')

print("✅ .env file created successfully!")
print("")
print("📋 API Key Setup Guide:")
print("=" * 50)
print("")
print("1. GROQ API KEY (REQUIRED - Free)")
print("   → Go to: https://console.groq.com")
print("   → Sign up / Log in")
print("   → Go to API Keys → Create new key")
print("   → Paste it as GroqAPIKey in .env")
print("")
print("2. COHERE API KEY (OPTIONAL - Free)")
print("   → Go to: https://dashboard.cohere.com")
print("   → Sign up / Log in")
print("   → Go to API Keys → Copy your key")
print("   → Paste it as CohereAPIKey in .env")
print("   → NOTE: App works without this (uses keyword classifier)")
print("")
print("3. HUGGING FACE TOKEN (OPTIONAL - Free)")
print("   → Go to: https://huggingface.co/settings/tokens")
print("   → Sign up / Log in")
print("   → Create new token (read access)")
print("   → Paste it as HuggingFaceAPIKey in .env")
print("   → NOTE: Only needed for image generation")
print("")
print("4. EDGE TTS (Built-in - No key needed)")
print("   → Text-to-speech works automatically")
print("")
print("5. CHROME WEBSPEECH (Built-in - No key needed)")
print("   → Speech recognition works via Chrome browser")
print("   → Make sure Google Chrome is installed")
print("")